### ISSUE TITLE
Bug in py3 version: malformed string

### ISSUE THREAD

**Issue by keflavich** [astroumd/admit#40]
@teuben any ideas?  I'm not sure if this is an incorrect filename definition or something else.
```
_ADMIT_ROOT= /orange/adamginsburg/repos/admit
ADMIT basedir   = /orange/adamginsburg/slurmjobs/W51-IRS2_B6_spw7_12M_spw7.admit
ADMIT root      = /orange/adamginsburg/repos/admit
ADMIT version   = 1.0.8.3
Traceback (most recent call last):
  File "/orange/adamginsburg/ALMA_IMF/reduction/analysis/admit_script.py", line 14, in <module>
    p = admit.Project(f'{basefn}.admit', dataserver=True)
  File "/orange/adamginsburg/repos/admit/admit/Admit.py", line 277, in __init__
    parser.parse()
  File "/orange/adamginsburg/repos/admit/admit/xmlio/Parser.py", line 184, in parse
    self.parser.parse(open(self.baseDir + self.xmlFile))
  File "/orange/adamginsburg/miniconda3/envs/casa6_py36/lib/python3.6/xml/sax/expatreader.py", line 111, in parse
    xmlreader.IncrementalParser.parse(self, source)
  File "/orange/adamginsburg/miniconda3/envs/casa6_py36/lib/python3.6/xml/sax/xmlreader.py", line 125, in parse
    self.feed(buffer)
  File "/orange/adamginsburg/miniconda3/envs/casa6_py36/lib/python3.6/xml/sax/expatreader.py", line 217, in feed
    self._parser.Parse(data, isFinal)
  File "/tmp/build/80754af9/python_1564510748219/work/Modules/pyexpat.c", line 473, in EndElement
  File "/orange/adamginsburg/miniconda3/envs/casa6_py36/lib/python3.6/xml/sax/expatreader.py", line 336, in end_element
    self._cont_handler.endElement(name)
  File "/orange/adamginsburg/repos/admit/admit/xmlio/AdmitParser.py", line 442, in endElement
    temp = aast.literal_eval(self.tempdata)
  File "/orange/adamginsburg/repos/admit/admit/util/admit_ast.py", line 97, in literal_eval
    return _convert(node_or_string)
  File "/orange/adamginsburg/repos/admit/admit/util/admit_ast.py", line 77, in _convert
    return list(map(_convert, node.elts))
  File "/orange/adamginsburg/repos/admit/admit/util/admit_ast.py", line 96, in _convert
    raise ValueError('malformed string')
ValueError: malformed string
```

**Comment by teuben** [comment]
which python are you using.  And are you running this as:
        python myscript.py

Mine current setup is a privately compiled Python3, but I've also tried anaconda3 in the past. Neither of those are showing me malformed strings.

I do have lots of matplotlib verbosities in in LineID, but that's awaiting CASA6 to give me my plotting back.

**Comment by keflavich** [comment]
`Python 3.6.9 :: Anaconda, Inc.`
Yes, `python <myscript>`.

This doesn't look like a matplotlib issue?  But I don't know what you're using AST for.

**Comment by teuben** [comment]
can you make sure the admit directory doesn't exist, this is a bug in the python3 system, you can't rerun yet
